### ISSUE TITLE
Error when loading local music source

### ISSUE THREAD

**Issue by oischinger** [music-assistant/server#145]
This project looks incredibly interesting.
Started to play with it and installed the Home Assistant addon but when trying to add local music in /meda (seems to be mounted into the container) I get this:
```
2021-08-08 18:27:34,070 DEBUG task_manager  -- Error while running task [Library sync of albums for provider Local files and playlists]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/music_assistant/managers/library.py", line 352, in library_albums_sync
    for item in await music_provider.get_library_albums():
TypeError: object async_generator can't be used in 'await' expression```

Any ideas what could be wrong? I did enter appropriate paths for the local files music source in the settings.

**Comment by marcelveldt** [comment]
Hi! Great to see some interest in my pet project :-)
The local music source needs some love after the last refactor. I'll do my best to fix this asap.

**Comment by marcelveldt** [comment]
I've implemented a basic fix so it should at least work but it needs more improvements on a later stage.
For now, music needs to be in structure artist\album\track.ext in the music folder.

**Comment by oischinger** [comment]
Thanks. that worked fine. My music collection loaded after making some adjustments to the tag parsing. I uploaded a PR here: https://github.com/music-assistant/server/pull/157

I noticed however that playing from the File source produces some serious buffering issues. It takes at least 20 seconds for the stream to start and then it stops multiple times until it actually plays.
Anything I should look out for?

**Comment by marcelveldt** [comment]
Did you notice the buffer issues on Chromecast devices perhaps ?

**Comment by oischinger** [comment]
Yes, only on Chromecast

**Comment by marcelveldt** [comment]
Yeah, it is a common issue with the default media receiver:
https://github.com/home-assistant-libs/pychromecast/issues/356

Something to try is enabling crossfade, which will switch to the internal queue streamer.
When summer is over I will do some work to stabilize things and implement a workaround for the buffering issue.

**Comment by oischinger** [comment]
Sounds great. I'll keep watching this space 🙂
