### ISSUE TITLE
music assistant streaming protocols

### ISSUE THREAD

**Issue by apaperclip** [music-assistant/server#171]
It was cool to see this! I'm glad you mentioned it.  Do you have any plans to support DLNA for streaming?

I've been looking for a non-windows based streaming service to replace Mezzmo. The power of Mezzmo for me are the active and dynamic playlists that determine the hierarchy of the folder structure when browsing via DLNA.  Nothing that I've found seems be as flexible. I wasn't sure what your roadmap was like and if you had plans for more advance features like this.

**Comment by marcelveldt** [comment]
Yeah, DLNA and Airplay support is on my TODO list.
Now that the dark winter days are coming I'l probably have some more time to invest in this project.

In fact, the first thing I want to implement was dynamic playlists as I have some really cool ideas for that.
I haven't look at DLNA yet bu I suppose it won't be that hard to implement. I guess you mean you'd like to browse the Music Assistant library from a DLNA compliant device, right ?
